In [1]:
import pandas as pd

In [11]:
raw_csv_data = pd.read_csv('Absenteeism_data.csv')

In [12]:
df = raw_csv_data.copy()

In [13]:
df

,ID,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,11,26,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,36,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,3,23,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,7,7,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,11,23,23/07/2015,289,36,33,239.554,30,1,2,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...
695,17,10,23/05/2018,179,22,40,237.656,22,2,2,0,8
696,28,6,23/05/2018,225,26,28,237.656,24,1,1,2,3
697,18,10,24/05/2018,330,16,28,237.656,25,2,0,0,8
698,25,23,24/05/2018,235,16,32,237.656,25,3,0,0,2
699,15,28,31/05/2018,291,31,40,237.656,25,1,1,1,2

### Drop 'ID'

In [14]:
df = df.drop(['ID'], axis = 1)

### Drop 'Age'

In [15]:
df_no_age = df.drop(['Age'], axis = 1)

In [16]:
age_dummies = pd.get_dummies(df['Age'])

In [17]:
age_dummies

,27,28,29,30,31,32,33,34,36,37,...,39,40,41,43,46,47,48,49,50,58
0,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
696,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
697,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
698,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
699,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False

In [18]:
age_dummies['check'] = age_dummies.sum(axis=1)
age_dummies

,27,28,29,30,31,32,33,34,36,37,...,40,41,43,46,47,48,49,50,58,check
0,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,1
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,1
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,1
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,1
4,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,1
696,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,1
697,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,1
698,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,1
699,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,1

In [19]:
age_dummies['check'].sum(axis=0)

np.int64(700)

In [20]:
age_dummies['check'].unique()

array([1])